server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:   # 주어진 데이터베이트에 액세스 권한을 가지고 있는 유저의 크레덴셜과, 연결을 원하는 데이터베이스에 대한 JDBC URL
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    driver-class-name: org.postgresql.Driver
    hikari:    # 데이터베이스와의 상호작용을 위한 연결 풀 설정
      connection-timeout: 2000   # 풀에서 연결 객체를 얻기 위해 기다려야 하는 최대 시간(ms)
      maximum-pool-size: 5        # 히카리 CP가 풀에 최대한으로 유지할 수 있는 연결 객체의 수
management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!
